context:
  version: "2.30"

package:
  name: stb
  version: ${{ version }}

source:
  url: https://github.com/nothings/stb/archive/2c980bb59875b0d32144a71867fbdebb2f77cd20.tar.gz
  sha256: 9a955b1b49a4410088a2e0ee2a9c057c3c907d0c1d75454144cb980aca0ba515

requirements:
  build:
    - python ==3.12.13

build:
  number: 0
  script:
    - if: win
      then: python "%RECIPE_DIR%/install.py"
      else: python "$RECIPE_DIR/install.py"

tests:
  - package_contents:
      include:
        - stb_image.h
      files:
        - licenses/stb/LICENSE

about:
  homepage: https://github.com/nothings/stb
  license: MIT OR Unlicense
  license_file: LICENSE
  repository: https://github.com/nothings/stb
  summary: Single-file public-domain or MIT-licensed libraries for C and C++.
