# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Core API for robot joint gain tuning and validation tests."""

from .base import RobotTest, TestResult
from .discretization_sweep import (
    DiscretizationSweepTest,
    aggregate_dt_sweep,
    dt_sweep_levels,
    select_target_level_index,
    validate_dt_bounds,
)
from .divergence import (
    DIVERGENCE_HEADROOM,
    clip_series_to_valid,
    divergence_limit,
    peak_bound,
    travel_bound,
    valid_prefix_length,
)
from .extension import Extension  # noqa: F401 (loaded for Kit extension discovery)
from .gain_save_targets import (
    GainSpecEdit,
    GainWriteTargets,
    MjcGainParams,
    MjcGainSource,
    SaveTargetCandidate,
    SaveTargetOptions,
    apply_gain_save_plan,
    author_mjc_gains,
    build_gain_save_plan,
    build_mjc_gain_map,
    drive_gains_to_mjc,
    get_defining_layer,
    list_gain_save_target_layers,
    resolve_gain_write_targets,
)
from .gain_sources import (
    ActuatorGains,
    GainLabels,
    GainReadContext,
    GainSource,
    ResolvedGains,
    available_viewed_sources,
    build_actuator_gain_map,
    gain_labels_for_source,
    has_physics_drive,
    is_viewed_source_editable,
    mjc_params_to_drive_gains,
    newton_mujoco_solver_active,
    newton_solver_type,
    resolve_joint_gains,
)
from .gain_tuner_drive_math import (
    damping_from_damping_ratio_position_drive,
    damping_ratio_from_stiffness_damping_position_drive,
    meq_for_drive_frequency,
    natural_frequency_hz_from_stiffness_position_drive,
    stiffness_and_damping_from_natural_frequency_position_drive,
    stored_gain_scale,
)
from .gains_tuner import (
    MAX_VELOCITY_AGREEMENT_REL_TOL,
    UNLIMITED_VELOCITY_THRESHOLD,
    GainsTestMode,
    GainTuner,
    JointListEntry,
    JointMode,
    SinusoidalTest,
    StepFunctionTest,
    max_velocity_agrees,
)
from .joint_drive_attrs import (
    JointDriveMode,
    get_damping_attr,
    get_joint_drive_mode,
    get_joint_drive_type_attr,
    get_stiffness_attr,
    is_joint_mimic,
)
from .joint_schema_attrs import (
    BACKEND_DISPLAY_LABELS,
    BACKEND_NEWTON,
    BACKEND_PHYSX,
    JOINT_PARAM_SPECS,
    NEWTON_DEFAULT_ARMATURE,
    NEWTON_JOINT_API,
    NEWTON_SOLVER_TYPES,
    PHYSX_JOINT_API,
    SCHEMA_JOINT_APIS,
    SCHEMA_LABELS,
    SCHEMA_MJC,
    SCHEMA_NEWTON,
    SCHEMA_PHYSX,
    SOLVER_MUJOCO,
    SOLVER_VBD,
    SOLVER_XPBD,
    SUPPORTED_BACKENDS,
    JointParamResolution,
    JointParamSpec,
    author_joint_param,
    authored_joint_param_attrs,
    authored_joint_param_values,
    backend_display_label,
    backend_reads_usd_while_playing,
    backend_supported,
    backend_write_schema,
    candidate_param_chains,
    copy_joint_param_to_backend,
    diverging_joint_params,
    joint_param_attrs,
    joint_param_spec,
    newton_backend_selected,
    other_backend,
    param_resolver_chain,
    resolve_joint_param,
    resolve_joint_params,
    resolver_chain,
)
from .snap_to_limits import SnapToLimitsTest
from .stress_test import StressTest, StressTestMode
from .usd_layer_utils import (
    collect_gain_save_edits,
    find_layer_by_save_identifier,
    is_layer_savable,
    is_physx_layer,
    plan_stage_layer_save,
)

__all__ = [
    "ActuatorGains",
    "BACKEND_DISPLAY_LABELS",
    "BACKEND_NEWTON",
    "BACKEND_PHYSX",
    "DIVERGENCE_HEADROOM",
    "DiscretizationSweepTest",
    "GainLabels",
    "GainReadContext",
    "GainSource",
    "GainSpecEdit",
    "GainTuner",
    "GainWriteTargets",
    "GainsTestMode",
    "JOINT_PARAM_SPECS",
    "JointDriveMode",
    "JointListEntry",
    "JointMode",
    "JointParamResolution",
    "JointParamSpec",
    "MAX_VELOCITY_AGREEMENT_REL_TOL",
    "MjcGainParams",
    "MjcGainSource",
    "NEWTON_DEFAULT_ARMATURE",
    "NEWTON_JOINT_API",
    "NEWTON_SOLVER_TYPES",
    "PHYSX_JOINT_API",
    "ResolvedGains",
    "RobotTest",
    "SCHEMA_JOINT_APIS",
    "SCHEMA_LABELS",
    "SCHEMA_MJC",
    "SCHEMA_NEWTON",
    "SCHEMA_PHYSX",
    "SOLVER_MUJOCO",
    "SOLVER_VBD",
    "SOLVER_XPBD",
    "SUPPORTED_BACKENDS",
    "SaveTargetCandidate",
    "SaveTargetOptions",
    "SinusoidalTest",
    "SnapToLimitsTest",
    "StepFunctionTest",
    "StressTest",
    "StressTestMode",
    "TestResult",
    "UNLIMITED_VELOCITY_THRESHOLD",
    "aggregate_dt_sweep",
    "apply_gain_save_plan",
    "author_joint_param",
    "author_mjc_gains",
    "authored_joint_param_attrs",
    "authored_joint_param_values",
    "available_viewed_sources",
    "backend_display_label",
    "backend_reads_usd_while_playing",
    "backend_supported",
    "backend_write_schema",
    "build_actuator_gain_map",
    "build_gain_save_plan",
    "build_mjc_gain_map",
    "candidate_param_chains",
    "clip_series_to_valid",
    "collect_gain_save_edits",
    "copy_joint_param_to_backend",
    "damping_from_damping_ratio_position_drive",
    "damping_ratio_from_stiffness_damping_position_drive",
    "divergence_limit",
    "diverging_joint_params",
    "drive_gains_to_mjc",
    "dt_sweep_levels",
    "find_layer_by_save_identifier",
    "gain_labels_for_source",
    "get_damping_attr",
    "get_defining_layer",
    "get_joint_drive_mode",
    "get_joint_drive_type_attr",
    "get_stiffness_attr",
    "has_physics_drive",
    "is_joint_mimic",
    "is_layer_savable",
    "is_physx_layer",
    "is_viewed_source_editable",
    "joint_param_attrs",
    "joint_param_spec",
    "list_gain_save_target_layers",
    "max_velocity_agrees",
    "meq_for_drive_frequency",
    "mjc_params_to_drive_gains",
    "natural_frequency_hz_from_stiffness_position_drive",
    "newton_backend_selected",
    "newton_mujoco_solver_active",
    "newton_solver_type",
    "other_backend",
    "param_resolver_chain",
    "peak_bound",
    "plan_stage_layer_save",
    "resolve_gain_write_targets",
    "resolve_joint_gains",
    "resolve_joint_param",
    "resolve_joint_params",
    "resolver_chain",
    "select_target_level_index",
    "stiffness_and_damping_from_natural_frequency_position_drive",
    "stored_gain_scale",
    "travel_bound",
    "valid_prefix_length",
    "validate_dt_bounds",
]
