#!/usr/bin/env python3
"""
PR Path Filter Check
====================
Validates that files changed in a PR comply with the external contribution
path policy defined in tools/github/ci/path_filter.yml.

Policy summary:
  - Every changed file must be under the configured allowed root
  - Every changed file must have a configured allowed suffix
  - For renames, both old and new paths must match
  - Symlinks, generated output, and binary/encoded content are not allowed

Usage:
    python3 tools/github/ci/check_path_filter.py <file_list>
    python3 tools/github/ci/check_path_filter.py -  (read from stdin)

    The file list may contain either plain paths (one per line) or TSV lines
    produced by `git diff-tree --raw --no-abbrev`:
        <blob_sha>\t<mode>\t<path>

Exit codes:
    0 - All paths allowed
    1 - One or more paths denied
"""

import os
import subprocess
import sys
from pathlib import Path

import yaml

_GENERATED_MARKERS = [
    b"# this file was auto-generated",
    b"# do not edit",
    b"# generated by",
    b"# auto-generated",
    b"/* auto-generated",
    b"/* generated by",
    b"// auto-generated",
    b"// generated by",
    b"// this file was auto-generated",
    b"// do not edit",
]

_NULL_BLOB = "0" * 40


_DEFAULT_CONFIG = Path(__file__).parent / "path_filter.yml"


def load_config(config_path: str | None = None) -> dict:
    """Load path filter config from YAML."""
    path = Path(config_path) if config_path else _DEFAULT_CONFIG
    with open(path) as f:
        return yaml.safe_load(f)


def check_path(filepath: str, allowed_root: str, allowed_suffixes: list) -> tuple:
    """
    Check a single file path against the policy.
    Returns (allowed: bool, reason: str).
    """
    if not filepath.startswith(allowed_root):
        return False, f"Path is outside the allowed root ({allowed_root})"

    suffix = os.path.splitext(filepath)[1]
    if suffix not in allowed_suffixes:
        if suffix:
            return False, f"Suffix '{suffix}' is not in the allowed list"
        else:
            return False, "File has no extension (suffix required)"

    return True, "Matches allowed root and suffix"


def _blob_content(blob_sha: str, max_bytes: int = 8192) -> bytes | None:
    """Return up to max_bytes of a git blob's content, or None on error."""
    if not blob_sha or blob_sha == _NULL_BLOB:
        return None
    try:
        result = subprocess.run(
            ["git", "cat-file", "blob", blob_sha],
            capture_output=True,
            timeout=10,
        )
        return result.stdout[:max_bytes] if result.returncode == 0 else None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def check_file(blob_sha: str, mode: str, filepath: str, allowed_root: str, allowed_suffixes: list) -> tuple:
    """
    Check a file against path policy and content rules.
    Returns (allowed: bool, reason: str).
    """
    ok, reason = check_path(filepath, allowed_root, allowed_suffixes)
    if not ok:
        return False, reason

    if mode == "120000":
        return False, "File is a symlink"

    # Deleted files (mode 000000) need no content check.
    if mode == "000000":
        return True, "Matches allowed root and suffix"

    content = _blob_content(blob_sha)
    if content is not None:
        if b"\x00" in content:
            return False, "File contains binary content (null bytes detected)"
        first_chunk = content[:1024].lower()
        for marker in _GENERATED_MARKERS:
            if marker in first_chunk:
                return False, f"File appears to be generated output (marker: '{marker.decode()}')"

    return True, "Matches allowed root and suffix"


def main():
    if len(sys.argv) < 2:
        print("Usage: check_path_filter.py <file_list_or_dash_for_stdin>")
        print("  Pass '-' to read from stdin, or provide a file path")
        sys.exit(2)

    if sys.argv[1] == "-":
        raw_lines = [line.strip() for line in sys.stdin if line.strip()]
    else:
        with open(sys.argv[1]) as f:
            raw_lines = [line.strip() for line in f if line.strip()]

    if not raw_lines:
        print("✅ No files to check")
        sys.exit(0)

    # Detect TSV format (blob_sha\tmode\tpath) vs plain path list.
    use_extended = "\t" in raw_lines[0]

    entries = []
    for line in raw_lines:
        if use_extended:
            parts = line.split("\t", 2)
            if len(parts) == 3:
                entries.append((parts[0], parts[1], parts[2]))
                continue
        entries.append(("", "", line))

    config = load_config()
    allowed_root = config["allowed_root"]
    allowed_suffixes = config["allowed_suffixes"]

    denied = []
    allowed = []

    for blob_sha, mode, filepath in entries:
        if use_extended and blob_sha:
            ok, reason = check_file(blob_sha, mode, filepath, allowed_root, allowed_suffixes)
        else:
            ok, reason = check_path(filepath, allowed_root, allowed_suffixes)

        if ok:
            allowed.append((filepath, reason))
        else:
            denied.append((filepath, reason))

    print(f"Files checked: {len(entries)}")
    print(f"  Allowed: {len(allowed)}")
    print(f"  Denied:  {len(denied)}")
    print()

    if allowed:
        print("✅ Allowed files:")
        for filepath, _ in allowed[:20]:
            print(f"  ✓ {filepath}")
        if len(allowed) > 20:
            print(f"  ... and {len(allowed) - 20} more")
        print()

    if denied:
        print("❌ The following files are not allowed in external PRs:")
        print()
        for filepath, reason in denied:
            print(f"  ✗ {filepath}")
            print(f"    → {reason}")
        print()
        print(
            "Policy: Only files under '{}' with suffixes {} are allowed.".format(
                allowed_root, ", ".join(allowed_suffixes)
            )
        )
        print()
        print("To propose a scope change, open a GitHub Issue or Discussion.")
        print("An NVIDIA maintainer must update the policy before additional")
        print("paths or file types become eligible.")
        sys.exit(1)
    else:
        print("✅ All changed files pass the path filter check")
        sys.exit(0)


if __name__ == "__main__":
    main()
