#!/usr/bin/env python3
"""Generate contributor-facing path-policy documentation from its YAML source."""

import argparse
import sys
from pathlib import Path

import yaml

_SCRIPT_DIRECTORY = Path(__file__).resolve().parent
_REPOSITORY_ROOT = _SCRIPT_DIRECTORY.parents[2]
_CONFIG_PATH = _SCRIPT_DIRECTORY / "path_filter.yml"
_DOCUMENT_PATH = _REPOSITORY_ROOT / "CONTRIBUTING_PATHS.md"
_LANGUAGE_NAMES = {
    ".c": "C source",
    ".cpp": "C++ source",
    ".cu": "CUDA source",
    ".cuh": "CUDA header",
    ".h": "C header",
    ".hpp": "C++ header",
    ".md": "Markdown",
    ".py": "Python",
    ".rst": "reStructuredText",
}


def load_policy() -> tuple[str, list[str]]:
    """Load the allowed root and suffixes from the machine-readable policy."""
    policy = yaml.safe_load(_CONFIG_PATH.read_text(encoding="utf-8"))
    return policy["allowed_root"], policy["allowed_suffixes"]


def render_document(allowed_root: str, allowed_suffixes: list[str]) -> str:
    """Render the contributor-facing Markdown document."""
    rows = []
    for suffix in allowed_suffixes:
        language = _LANGUAGE_NAMES.get(suffix, suffix)
        rows.append(f"| {language} | `{allowed_root}**/*{suffix}` |")
    allowed_rows = "\n".join(rows)

    return f"""# External contribution path policy

<!-- Generated by tools/github/ci/generate_path_policy_docs.py. Do not edit directly. -->

The machine-readable policy in
[`tools/github/ci/path_filter.yml`](tools/github/ci/path_filter.yml) is the
authoritative allowlist for external contributions. This document presents that
policy for contributors. CI rejects this file when it is not synchronized with
the machine-readable policy.

Every path changed by an external commit must match both the allowed root and
one allowed suffix. Paths and suffixes are case-sensitive.

## Allowed paths

| Language | Allowed repository-relative pattern |
| --- | --- |
{allowed_rows}

The policy applies to added, modified, and deleted files. For a rename, both
the old path and the new path must match. An allowed path must contain ordinary
source text; symlinks, generated output, and binary or encoded content are not
allowed.

## Everything else is denied

Files outside `{allowed_root}` and files with any other suffix are not
open to external modification. This includes:

- Extension manifests and build files such as `.toml` and `.lua`.
- OmniGraph, configuration, and schema files such as `.ogn`, `.json`, `.yaml`,
  `.yml`, `.xml`, and `.proto`.
- Assets, datasets, archives, executables, and other binary files.
- Python bytecode and generated source or documentation.
- Repository infrastructure, dependencies, workflows, and this policy.

There are no pull-request exceptions to this initial allowlist. Propose a scope
change through a GitHub Issue or Discussion. An NVIDIA maintainer must update
the machine-readable policy before an additional path or suffix becomes
eligible.
"""


def main() -> int:
    """Write the document or verify that the committed document is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the document is not current.")
    arguments = parser.parse_args()

    allowed_root, allowed_suffixes = load_policy()
    expected_document = render_document(allowed_root, allowed_suffixes)

    if arguments.check:
        try:
            actual_document = _DOCUMENT_PATH.read_text(encoding="utf-8")
        except OSError as error:
            print(f"Unable to read {_DOCUMENT_PATH}: {error}", file=sys.stderr)
            return 1
        if actual_document != expected_document:
            print(
                f"{_DOCUMENT_PATH.name} is stale; run {Path(__file__).name} and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{_DOCUMENT_PATH.name} matches {_CONFIG_PATH.name}.")
        return 0

    _DOCUMENT_PATH.write_text(expected_document, encoding="utf-8")
    print(f"Updated {_DOCUMENT_PATH}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
